### ISSUE TITLE
SDK throws an exception when running in multiple threads

### ISSUE THREAD

**Issue by paddypawprints** [PitneyBowes/pitneybowes-shipping-api-csharp#9]
Starting task 0
Starting task 1
Starting task 2
Starting task 3
Starting task 4
Starting task 5
Starting task 6
Starting task 7
Starting task 8
Starting task 9
Label 10 d3108e61-f9ec-4278--10-0 created:USPS2200097171518853
Label 6 d3108e61-f9ec-4278--6-0 created:USPS2200097171525498
Label 10 d3108e61-f9ec-4278--10-1 created:USPS2200096973233505
Label 10 d3108e61-f9ec-4278--10-1 created:USPS2200096973227015
Label 10 d3108e61-f9ec-4278--10-2 created:USPS2200096973248218
Label 10 d3108e61-f9ec-4278--10-2 created:USPS2200097171538145
Label 10 d3108e61-f9ec-4278--10-3 created:USPS2200096973251550
Label 10 d3108e61-f9ec-4278--10-3 created:USPS2200097171543845
Label 10 d3108e61-f9ec-4278--10-4 created:USPS2200096973274858
Label 10 d3108e61-f9ec-4278--10-4 created:USPS2200096973263509
Label 10 d3108e61-f9ec-4278--10-5 created:USPS2200097171552406
Label 10 d3108e61-f9ec-4278--10-6 created:USPS2200097171563243
Label 10 d3108e61-f9ec-4278--10-7 created:USPS2200096973285133
Label 10 d3108e61-f9ec-4278--10-8 created:USPS2200096973298324
Label 10 d3108e61-f9ec-4278--10-9 created:USPS2200097171571127
Label 10 d3108e61-f9ec-4278--10-10 created:USPS2200097171588673
Label 10 d3108e61-f9ec-4278--10-11 created:USPS2200096973309207
Label 10 d3108e61-f9ec-4278--10-12 created:USPS2200096973316344
Label 10 d3108e61-f9ec-4278--10-13 created:USPS2200096973326248
Label 10 d3108e61-f9ec-4278--10-14 created:USPS2200097171591817
Label 10 d3108e61-f9ec-4278--10-15 created:USPS2200097171601193
Label 10 d3108e61-f9ec-4278--10-16 created:USPS2200097171617340
Label 10 d3108e61-f9ec-4278--10-17 created:USPS2200096973334234
Label 10 d3108e61-f9ec-4278--10-18 created:USPS2200097171629800
Label 10 d3108e61-f9ec-4278--10-19 created:USPS2200097171631082

Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (An item with the same key has already been added. Key: user-agent) (An item with the same key has already been added. Key: user-agent) (An item with the same key has already been added. Key: user-agent) (An item with the same key has already been added. Key: user-agent) (Object reference not set to an instance of an object.) (An item with the same key has already been added. Key: user-agent) (An item with the same key has already been added. Key: user-agent) (An item with the same key has already been added. Key: user-agent) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.Headers.HttpHeaders.AddHeaderToStore(String name, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(String name)
   at System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo(String name, Boolean parseRawValues)
   at System.Net.Http.Headers.HttpHeaderValueCollection`1.Add(T item)
   at PitneyBowes.Developer.ShippingApi.ShippingApiHttpRequest.<HttpRequestStatic>d__2`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PitneyBowes.Developer.ShippingApi.ShippingApiHttpRequest.<HttpRequest>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PitneyBowes.Developer.ShippingApi.TokenMethods.<token>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PitneyBowes.Developer.ShippingApi.WebMethod.<Request>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PitneyBowes.Developer.ShippingApi.WebMethod.<Post>d__2`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PitneyBowes.Developer.ShippingApi.Api.<CreateShipment>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyShip.Program.print(String s, Int32 i, Int32 j) in /Users/patrickfarry/Projects/MyShip/MyShip/Program.cs:line 72
   at MyShip.Program.<>c__DisplayClass0_1.<Main>b__0() in /Users/patrickfarry/Projects/MyShip/MyShip/Program.cs:line 30
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at MyShip.Program.Main(String[] args) in /Users/patrickfarry/Projects/MyShip/MyShip/Program.cs:line 35
bash: line 1: 48408 Abort trap: 6           "/usr/local/share/dotnet/dotnet" "/Users/patrickfarry/Projects/MyShip/MyShip/bin/Debug/netcoreapp2.0/MyShip.dll"

**Comment by paddypawprints** [comment]
Here is the code:

using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using PitneyBowes.Developer.ShippingApi;
using PitneyBowes.Developer.ShippingApi.Model;
using PitneyBowes.Developer.ShippingApi.Fluent;

namespace MyShip
{
    class Program
    {
        static void Main(string[] args)
        {
            var sandbox = new Session() { EndPoint = "https://api-sandbox.pitneybowes.com", Requester = new ShippingApiHttpRequest() };

            sandbox.AddConfigItem("ApiKey", "hjyWnfAcjG1rVzizKAq0uyExJY6VGW55");
            sandbox.AddConfigItem("ApiSecret", "QLmKAPLtogmnc93o");
            sandbox.AddConfigItem("ShipperID", "9014888410");
            sandbox.AddConfigItem("DeveloperID", "46841939");

            Model.RegisterSerializationTypes(sandbox.SerializationRegistry);
            Globals.DefaultSession = sandbox;
            string s = Guid.NewGuid().ToString().Substring(0,19);
            List<Task> TaskList = new List<Task>();
            for (int i = 0; i < 1; i++)
            {
                Console.WriteLine("Starting task {0}", i);
                var LastTask = new Task(()=> {
                    for (int j = 0; j < 100; j++) 
                        print(s, i, j);
                });
                LastTask.Start();
                TaskList.Add(LastTask);
            }
            Task.WaitAll(TaskList.ToArray());

            foreach (var ctr in sandbox.Counters)
            {
                foreach (var c in ctr.Value.CallHistogram)
                {

                    Console.WriteLine("{0},{1},{2}", ctr.Key, c.Key, c.Value);
                }
            }
        }

        static void print( string s, int i, int j )
        {
            var shipment = ShipmentFluent<Shipment>.Create()
                .ToAddress((Address)AddressFluent<Address>.Create()
                    .AddressLines("643 Greenway Rd")
                    .PostalCode("28607")
                    .CountryCode("US"))
               .FromAddress((Address)AddressFluent<Address>.Create()
                    .Company("Pitney Bowes Inc")
                    .AddressLines("27 Waterview Drive")
                    .CityTown("Shelton").StateProvince("CT").PostalCode("06484")
                    .CountryCode("US")
                    )
               .Parcel((Parcel)ParcelFluent<Parcel>.Create()
                    .Dimension(12, 12, 10)
                    .Weight(16m, UnitOfWeight.OZ))
               .Rates(RatesArrayFluent<Rates>.Create()
                    .USPSPriority<Rates, Parameter>())
               .Documents((List<IDocument>)DocumentsArrayFluent<Document>.Create()
                    .ShippingLabel(ContentType.URL, Size.DOC_4X6, FileFormat.PDF))
               .ShipmentOptions(ShipmentOptionsArrayFluent<ShipmentOptions>.Create()
                    .ShipperId("9014888410")
                    )
               .TransactionId( string.Format("{0}-{1}-{2}", s, i, j));

            var label = Api.CreateShipment((Shipment)shipment).GetAwaiter().GetResult();
            if (label.Success)
            {
                Console.WriteLine("Label {0} {1} created:{2}", i, string.Format("{0}-{1}-{2}", s, i, j), label.APIResponse.ShipmentId);
            }
            else
            {
                Console.WriteLine("Label {0} {1} failed:{1}", i, string.Format("{0}-{1}-{2}", s, i, j, label.HttpStatus));
                foreach( var e in label.Errors)
                {
                    Console.WriteLine("    {0} {1}", e.ErrorCode, e.Message);
                }
            }
        }
    }
}

Running .net core 2.0 on OSX Sierra

**Comment by pa009fa** [comment]
Issue is in pitneybowes-shipping-api-csharp/src/webservice/ShippingApiHttpRequest.cs
Code is using client.DefaultRequestHeaders, rather than request headers.

See this https://stackoverflow.com/questions/29801195/adding-headers-when-using-httpclient-getasync

        var requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://your.site.com");
        requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", your_token);
        httpClient.SendAsync(requestMessage);

**Comment by paddypawprints** [comment]
Fixed in latest nuget package,
